import type { Theme } from "@/types";
export const themes: Theme[] = [
  {
    name: "Apology",
    background: "linear-gradient(180deg, #f8fafc, #e5e7eb)",
    textColor: "#1f2937",
    placeholderColor: "#6b7280",
    fontFamily: "'Georgia', serif",
    borderColor: "#d1d5db",
    buttonBackground: "#64748b",
    buttonTextColor: "#ffffff",
    accentColor: "#475569",
  },
  {
    name: "Regret",
    background: "linear-gradient(180deg, #0f172a, #1e293b)",
    textColor: "#e5e7eb",
    placeholderColor: "#9ca3af",
    fontFamily: "'Times New Roman', serif",
    borderColor: "#334155",
    buttonBackground: "#475569",
    buttonTextColor: "#ffffff",
    accentColor: "#94a3b8",
  },
  {
    name: "Confession",
    background: "linear-gradient(135deg, #fde2e4, #fbcfe8)",
    textColor: "#4a044e",
    placeholderColor: "#9d174d",
    fontFamily: "'Playfair Display', serif",
    borderColor: "#f9a8d4",
    buttonBackground: "#db2777",
    buttonTextColor: "#ffffff",
    accentColor: "#be185d",
  },
  {
    name: "Bold Love",
    background: "linear-gradient(135deg, #ff6a88, #ff99ac)",
    textColor: "#2b0a12",
    placeholderColor: "#7f1d1d",
    fontFamily: "'Great Vibes', cursive", 
    borderColor: "#fb7185",
    buttonBackground: "#be123c",
    buttonTextColor: "#ffffff",
    accentColor: "#9f1239",
  },
  {
    name: "Playful",
    background: "linear-gradient(135deg, #fef3c7, #fde68a)",
    textColor: "#78350f",
    placeholderColor: "#a16207",
    fontFamily: "'Comic Neue', cursive",
    borderColor: "#facc15",
    buttonBackground: "#f59e0b",
    buttonTextColor: "#000000",
    accentColor: "#d97706",
  },
  {
    name: "Chaos",
    background: "linear-gradient(135deg, #a78bfa, #f472b6)",
    textColor: "#1f2937",
    placeholderColor: "#374151",
    fontFamily: "'Poppins', sans-serif",
    borderColor: "#c084fc",
    buttonBackground: "#9333ea",
    buttonTextColor: "#ffffff",
    accentColor: "#ec4899",
  }

];
